
machines=[
	{
		:hostname => "jcervoniS",
		:name => "jcervoni",
		:ip => "192.168.56.110",
		:box => "generic/debian10",
		:ram => 1024,
		:cpu => 1
	},
	{
		:hostname => "jcervoniSW",
		:name => "melperri",
		:ip => "192.168.56.111",
		:box => "generic/debian10",
		:ram => 1024,
		:cpu => 1
	}
]

Vagrant.configure("2") do |config|
	machines.each do |machine|
		config.vm.define machine[:hostname] do |node|
			node.vm.box = machine[:box]
			node.vm.hostname = machine[:hostname]
			node.vm.network "public_network", ip: machine[:ip]
			node.vm.provider "virtualbox" do |vb|
				vb.name = machine[:name]
				vb.memory = machine[:ram]
				vb.cpus = machine[:cpu]
			end
		end
	end
end

# Vagrant.configure("2") do |config|
# 	config.vm.box = "generic/debian10"
# 	config.vm.hostname = "jcervoniS"
# 	config.vm.name = "jcervoni"
# end