apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42-playground
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/ElRealMitch/jcervoni-IoT-apps.git/
    targetRevision: HEAD
    path: playground
  destination: # in-cluster ?
    name: IoT
    namespace: dev
    server: https://kubernetes.default.svc/
  project: default
  syncPolicy:
    automated: {}