apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil42-playground
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/ElRealMitch/jcervoni-IoT-apps'
    targetRevision: HEAD
    path: playground
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true